name: Release

on:
    push:
        branches:
            - main
        paths:
            - '.changeset/**'
            - '.github/workflows/release.yml'
    workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup pnpm 8
              uses: pnpm/action-setup@v2
              with:
                  version: 8.6.9

            - name: Setup Node.js 18.x
              uses: actions/setup-node@v2
              with:
                  node-version: 18.x

            - name: Install Dependencies
              run: pnpm i

            - name: Create Release Pull Request or Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  # This expects you to have a script called release which does a build for your packages and calls changeset publish
                  publish: pnpm release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            # - name: Send a Slack notification if a publish happens
            #   if: steps.changesets.outputs.published == 'true'
            #   # You can do something when a publish happens.
            #   run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
