import {cn} from 'mxcn';
import type {Metadata} from 'next';
import {Inter as FontSans} from 'next/font/google';
import './globals.css';

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
});

export const metadata: Metadata = {
	title: '⌘ Langbase with a Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					'min-h-screen bg-background font-sans antialiased',
					fontSans.variable,
				)}
			>
				{/* <div className="flex min-h-screen flex-col items-center justify-between p-24"> */}
				{/* <div className="flex flex-col items-center justify-between gap-10 max-w-lg w-full"> */}
				<div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
					{children}
				</div>
				{/* </div> */}
				{/* </div> */}
			</body>
		</html>
	);
}
